### ISSUE TITLE
Example readme

### ISSUE THREAD

**Issue by carloszimm** [mostjs-community/from-array#1]
Hey, @hoichi!

I found some issues in the readme example:

- Missing parentheses on the **fromArray** call
- **mapped** is not defined (I think you meant the stream constant)

**Comment by hoichi** [comment]
Done.

I guess my example used `map` at some point, for beefiness, I guess, but then I removed it as irrelevant.

I also fixed the file name in `dist/`: it was still being called `most-from-event` because of copy/paste.

Thanks for the heads up, @carloszimm!
